#-------------------------------
# General Site Settings
title: Yachika Anand
description: "Hi, Iâ€™m Yachika â€“ a data enthusiast who loves turning questions into insights and insights into impact.
I explore the world through data, AI, and education, constantly learning and sharing how technology, especially machine learning and deep learning, can solve real-world problems and inspire smarter decisions.

ðŸ“Š My Journey So Far

Masterâ€™s in Information Technology with a strong foundation in data analytics, AI, machine learning (ML), deep learning (DL), Cloud, and Data Engineering tools with secure web practices .

Skilled in Python (Pandas, NumPy, Scikit-learn, TensorFlow, Keras, Matplotlib, Seaborn), SQL, Power BI, and Tableau.

Hands-on with EDA, data wrangling, data cleaning, model building, hyperparameter tuning, and evaluating ML/DL models.

Experienced in ETL pipelines using PySpark, Databricks, and version-controlled workflows with Docker.

ðŸ§  What Excites Me

Building predictive models with machine learning and exploring neural networks through deep learning.

Simplifying technical concepts to make data science approachable and fun.

Discovering patterns in data and communicating them through compelling visualizations and dashboards.

ðŸš€ Currently Exploring

Deep learning frameworks like TensorFlow and PyTorch

Data engineering workflows, MLOps, and cloud-based environments

Creative ways to blend analytics, storytelling, and mentorship"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Ontario, Canada"
resume_url: "https://vidhyav656.github.io"
avatar_image: /img/avatar.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/yachikanand/" # Add your linkedln handle
github: "https://github.com/yachika-yashu/yachika-yashu"  # Add your github handle

#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: true


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
